openapi: 3.0.3
info:
  title: Kafka Streams Controllers
  description: Kafka Streams Controllers
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
tags:
  - name: Producer Manager
paths:
  /producer:
    post:
      tags:
        - Producer Manager
      summary: Activate or deactivate the producer
      description: Activate or deactivate the producer
      parameters:
        - in: query
          name: action
          required: true
          schema:
            type: string
            enum: [activate, deactivate]
      responses:
        '200':
          description: Successfully performed action on producer
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Producer activated successfully
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid action provided
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unexpected error occurred
